---
- hosts: localhost
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: write the apache conf file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf


